parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
extends:
  - alloy
  - alloy/typescript
  - eslint:recommended
  - plugin:jest/recommended
  - plugin:unicorn/recommended
  - plugin:@typescript-eslint/recommended
  - prettier
ignorePatterns:
  - coverage/
  - dist/
  - tests/*.js
rules:
  max-params: ["error", 4]
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'
  unicorn/switch-case-braces: ["error", "avoid"]
  unicorn/no-nested-ternary: off
  unicorn/no-null: off
  unicorn/prevent-abbreviations:
    - error
    - allowList:
        tmp: true
        args: true
        dist: true
        OTimerGetTimesArgs: true
