name: Tag, Release, and Publish on PR Merge to Master

on:
  pull_request:
    types:
      - closed

jobs:
  branch_master:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Merge Status on Master
        if: github.event.pull_request.base.ref == 'master' && github.event.pull_request.merged == true
        run: echo "MASTER_IS_MERGED=true" >> $GITHUB_ENV

  project_version:
    runs-on: ubuntu-latest
    needs: branch_master
    steps:
      - name: Checkout Code
        if: ${{ env.MASTER_IS_MERGED }} == 'true'
        uses: actions/checkout@v3

      - name: Install Node.js and jq
        if: ${{ env.MASTER_IS_MERGED }} == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Get Version from package.json
        if: ${{ env.MASTER_IS_MERGED }} == 'true'
        run: echo "PROJECT_VERSION=$(jq -r .version ./package.json)" >> $GITHUB_ENV

      - name: Check if Tag Exists
        if: ${{ env.MASTER_IS_MERGED }} == 'true'
        run: |
          tag="v${{ env.PROJECT_VERSION }}"
          if git rev-parse $tag >/dev/null 2>&1; then
            echo "::error::Tag v${{ env.PROJECT_VERSION }} already exists."
          fi

  tag:
    runs-on: ubuntu-latest
    needs: project_version
    steps:
      - name: Create and Push Tag
        if: ${{ env.MASTER_IS_MERGED }} == 'true'
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          tag="v${{ env.PROJECT_VERSION }}"
          git tag -a "v${{ tag }}" -m "Release v${{ $tag }}"
          git push origin "v${{ $env.PROJECT_VERSION }}"

  release:
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - name: Checkout Code
        if: ${{ env.MASTER_IS_MERGED }} == 'true'
        uses: actions/checkout@v3

      - name: Install Node.js
        if: ${{ env.MASTER_IS_MERGED }} == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        if: ${{ env.MASTER_IS_MERGED }} == 'true'
        run: npm install

      - name: Run Build
        if: ${{ env.MASTER_IS_MERGED }} == 'true'
        run: npm run build

      - name: Create GitHub Release
        if: ${{ env.MASTER_IS_MERGED }} == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v${{ env.PROJECT_VERSION }}" "dist/*" --title "Release v${{ env.PROJECT_VERSION }}" --notes "Release notes for v${{ env.PROJECT_VERSION }}"

  publish:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Publish as NPM Package
        if: ${{ env.MASTER_IS_MERGED }} == 'true'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
          npm publish
