name: Validate Pull Request to Master

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js and jq
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Build
        run: npm run build

      - name: Run Linter
        run: npm run lint

      - name: Run Tests
        run: npm run test

  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js and jq
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Get Version from package.json
        run: echo "PROJECT_VERSION=$(jq -r .version ./package.json)" >> $GITHUB_ENV

      - name: Check if Tag Exists
        run: |
          tag="v${{ env.PROJECT_VERSION }}"
          if git rev-parse $tag >/dev/null 2>&1; then
            echo "::error::Tag v${{ env.PROJECT_VERSION }} already exists."
          fi
